### ISSUE TITLE
Make gears uniform

### ISSUE THREAD

**Issue by Holysweet** [MaienM/ThisIsFine#11]
multiple gears are sharing recipes which makes it easy to graft the wrong gear and some recipes want a specific gear (so either split recipes for gears or start diggin through everything that has gears.....)

**Comment by MaienM** [comment]
Various mods add recipes with various gears, with wood being especially common. We will keep the Thermal Expansion versions, and the Ender IO versions for the ones that are not in Thermal Expansion.

- [ ] AE2
- [ ] Ender IO
- [ ] Better With Mods
