### ISSUE TITLE
Ender bucket fix

### ISSUE THREAD

**Issue by Holysweet** [MaienM/ThisIsFine#16]
Replace iron bars in recipe to Iron plate from immersive engineering

**Comment by Holysweet** [comment]
`recipes.addShaped(<randomthings:enderbucket>, [[null, null, null],[<immersiveengineering:metal:39>, null, <immersiveengineering:metal:39>], [null, <minecraft:ender_pearl>, null]]);
`

**Comment by alexanderheuts** [comment]
Fixed
