### ISSUE TITLE
Water to salt recipe needs to be enabled

### ISSUE THREAD

**Issue by alexanderheuts** [MaienM/ThisIsFine#19]
- [ ] iron bucket version
- [ ] clay bucket version

**Comment by Holysweet** [comment]
actually its the recipe from Pam's harvestcraft that turns Fresh water (looks like a barrel) into salt with a cooking pot that is disabled and should be turned back on.

and we might also remove the Fresh water to 8 Fresh water recipe that seems to not do anything if that exists after turning the salt one back on.

**Comment by Holysweet** [comment]
`recipes.addShapeless(<animania:salt>, [<harvestcraft:potitem>,<harvestcraft:freshwateritem>]);
`

**Comment by Holysweet** [comment]
the kitchen seems to be able to make salt just fine so imo this one would also not be needed anymore
