### ISSUE TITLE
Add chest recipe to change any wooden chest to oak chest

### ISSUE THREAD

**Issue by Holysweet** [MaienM/ThisIsFine#34]
because quark adds wood type specific chests

**Comment by MaienM** [comment]
Would it not make more sense to adjust recipes that only accept a wooden chest to accept any kind of chest instead? I'm not a fan of "convert into base version" recipes as a workaround for recipes that are too narrow in what they accept.

**Comment by Holysweet** [comment]
agreed will keep an eye out for recipes that are oak chest only

**Comment by MaienM** [comment]
I will close this issue then, we can create new issues as we find problematic recipes.
