### ISSUE TITLE
Add bonemeal recipes to rustic mortar and pestle

### ISSUE THREAD

**Issue by Holysweet** [MaienM/ThisIsFine#38]
Pams mortar and pestle with 1 bone yielding 5 bonemeal?

**Comment by MaienM** [comment]
What should the recipe be? How much should it yield?

**Comment by Holysweet** [comment]
think we decided on the mortar en pestle from rustic so this one is closed

**Comment by MaienM** [comment]
The recipes still have to be added for this, so let's keep this open until that's done.
