### ISSUE TITLE
Simplify Coke brick recipe

### ISSUE THREAD

**Issue by Holysweet** [MaienM/ThisIsFine#7]
Change to Coke oven bricks

**Comment by Holysweet** [comment]
`recipes.addShaped(<immersiveengineering:stone_decoration>, [[<minecraft:brick>, <immersiveengineering:stone_decoration:5>, <minecraft:brick>],[<immersiveengineering:stone_decoration:5>, <thermalfoundation:storage_resource>, <immersiveengineering:stone_decoration:5>], [<minecraft:brick>, <immersiveengineering:stone_decoration:5>, <minecraft:brick>]]);
recipes.addShaped(<immersiveengineering:stone_decoration>, [[<minecraft:brick>, <immersiveengineering:stone_decoration:5>, <minecraft:brick>],[<immersiveengineering:stone_decoration:5>, <minecraft:coal_block>, <immersiveengineering:stone_decoration:5>], [<minecraft:brick>, <immersiveengineering:stone_decoration:5>, <minecraft:brick>]]);`

**Comment by MaienM** [comment]
Is this still relevant, or was this something done by a since-removed script? The default recipe is clay + bricks + sand, the replacement is concrete + bricks + coal. If anything, that seems more complicated, adding an extra step that includes crafting with fluids.

**Comment by Holysweet** [comment]
not really no coz you don't have to gate it behind a bucket coz it can't really be used without a bucket anyways
